name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-tests:
    name: Python Lint & Tests
    runs-on: ubuntu-latest
    env:
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
      FAKE_OPENAI: ${{ secrets.FAKE_OPENAI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
          pip install pre-commit

      - name: Run Pre-commit Hooks
        run: pre-commit run --all-files

      - name: Run Linters (black, isort, flake8, mypy)
        run: |
          black . --check
          isort . --check-only
          flake8 . --max-line-length=100 --ignore=E203,W503
          mypy .

      - name: Run Unit & Integration Tests with Coverage
        run: pytest --cov=. --cov-report=xml

      - name: Detect Secrets
        run: detect-secrets scan --baseline .secrets.baseline

      - name: Upload Python coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: python
          name: codecov-python

  javascript-tests:
    name: JavaScript (Jest) Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node Dependencies
        run: npm install

      - name: Run Jest Tests with Coverage
        run: npx jest --coverage

      - name: Upload JS Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: javascript
          name: codecov-javascript
