name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
      FAKE_OPENAI: ${{ secrets.FAKE_OPENAI }}


    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run Tests
        run: pytest


      - name: Run linters (black, isort, flake8, mypy)
        run: |
          black . --check
          isort . --check-only
          flake8 .
          mypy .

      - name: Run tests
        run: |
          pytest tests

      - name: Detect secrets in code
        run: |
          pip install detect-secrets
          detect-secrets scan --baseline .secrets.baseline
