name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}
      FAKE_OPENAI: ${{ secrets.FAKE_OPENAI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install pre-commit

      - name: Run Pre-commit Hooks
        run: pre-commit run --all-files

      - name: Run Linters (black, isort, flake8, mypy)
        run: |
          black . --check
          isort . --check-only
          flake8 . --max-line-length=100 --ignore=E203,W503
          mypy .

      - name: Run Unit & Integration Tests with Coverage
        run: |
          pytest --cov=MultiAgentChatBot --cov-report=xml

      - name: Detect Secrets
        run: |
          detect-secrets scan --baseline .secrets.baseline

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

